services:
    app:
        build: ./
        restart: on-failure
        depends_on:
            # Makes the postgres service start first, but we still need
            # application-level code to make sure the service is actually ready.
            - postgres
        deploy:
            replicas: 2  
    nginx:
        build: ./gateway
        ports:
            - 80:80
        depends_on:
            - app
    postgres:
        build: ./db
        volumes:
            - pgdata:/var/lib/postgresql/data
volumes:
    # By providing only the volume name, we are using the container engine's
    # default configuration for creating a volume.
    pgdata:
